import type { CSSProperties } from 'react';

export const brand = {
  primary: '#5D1E69',
  primaryDark: '#40154A',
  accent: '#FA66AF',
  canvas: '#FBF6F9',
  surface: '#FFFFFF',
  border: '#EBDCE4',
  text: '#2E2233',
  mutedText: '#7C6C79',
  danger: '#C0392B',
  success: '#1E7D32',
  headingFont: "'Poppins', system-ui, sans-serif",
  bodyFont: "'Quicksand', system-ui, sans-serif",
};

export const ui: Record<string, CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: brand.canvas,
    fontFamily: brand.bodyFont,
    color: brand.text,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 32px',
    background: brand.surface,
    borderBottom: `1px solid ${brand.border}`,
  },
  content: {
    padding: 32,
    maxWidth: 960,
    margin: '0 auto',
  },
  card: {
    background: brand.surface,
    border: `1px solid ${brand.border}`,
    borderRadius: 16,
    boxShadow: '0 2px 14px rgba(93, 30, 105, 0.06)',
  },
  pageTitle: {
    fontFamily: brand.headingFont,
    fontSize: 22,
    fontWeight: 600,
    color: brand.primary,
    margin: 0,
  },
  pageSubtitle: {
    fontSize: 14,
    color: brand.mutedText,
    margin: '6px 0 0',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: 13,
    fontWeight: 600,
    color: brand.text,
  },
  input: {
    padding: '11px 14px',
    borderRadius: 10,
    border: `1px solid ${brand.border}`,
    fontSize: 14,
    fontFamily: brand.bodyFont,
    color: brand.text,
    background: brand.surface,
  },
  buttonPrimary: {
    padding: '12px 18px',
    borderRadius: 10,
    border: 'none',
    background: brand.primary,
    color: '#ffffff',
    fontWeight: 600,
    fontFamily: brand.bodyFont,
    fontSize: 14,
    cursor: 'pointer',
  },
  buttonSecondary: {
    padding: '10px 16px',
    borderRadius: 10,
    border: `1px solid ${brand.border}`,
    background: 'transparent',
    color: brand.text,
    fontWeight: 600,
    fontFamily: brand.bodyFont,
    fontSize: 13,
    cursor: 'pointer',
  },
  linkButton: {
    background: 'none',
    border: 'none',
    color: brand.primary,
    fontSize: 13,
    fontFamily: brand.bodyFont,
    cursor: 'pointer',
    textDecoration: 'underline',
    padding: 0,
  },
  error: {
    color: brand.danger,
    fontSize: 13,
    margin: 0,
  },
  success: {
    color: brand.success,
    fontSize: 13,
    margin: 0,
  },
  emptyState: {
    padding: '48px 24px',
    textAlign: 'center',
    color: brand.mutedText,
    fontSize: 14,
  },
};
